import 'package:flutter/material.dart';

import 'package:lettuce_travel/l10n/app_localizations.dart' show AppL10n;

/// Small ergonomics helpers used across the UI.
extension BuildContextX on BuildContext {
  /// Localized strings for the active locale. Generated by `flutter gen-l10n`
  /// (runs automatically on `flutter pub get` because `generate: true` is set
  /// in pubspec.yaml) — see the environment note in CLAUDE.md.
  AppL10n get l10n => AppL10n.of(this);

  ThemeData get theme => Theme.of(this);

  ColorScheme get colors => Theme.of(this).colorScheme;

  TextTheme get text => Theme.of(this).textTheme;

  /// True when the active locale is right-to-left. Prefer directional widgets
  /// over branching on this, but it is occasionally needed for icons.
  bool get isRtl => Directionality.of(this) == TextDirection.rtl;

  Size get screenSize => MediaQuery.sizeOf(this);

  void showSnack(String message, {bool isError = false}) {
    ScaffoldMessenger.of(this)
      ..hideCurrentSnackBar()
      ..showSnackBar(
        SnackBar(
          content: Text(message),
          backgroundColor: isError ? colors.error : null,
        ),
      );
  }
}
